# Generated by Django 4.2.1 on 2023-05-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_detail',
            new_name='name',
        ),
    ]
